spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
